server:
  port: 8081

#配置文件默认dev
spring:
  profiles:
    active: ds, dev

# 关闭security默认
security:
  basic:
    enabled: false
mybatis:
  typeAliasesPackage: org.ko.framework.data.*.domain #小名
  mapperLocations: classpath:mappers/*.xml  #mapper扫描
  configuration:
    mapUnderscoreToCamelCase: true #开始下划线转驼峰

