server:
  port: 8081

#配置文件默认dev
spring:
  profiles:
    active: dev
  data:
    redis:
      repositories:
        enabled: false

# 关闭security默认
security:
  basic:
    enabled: false

# mybatis 配置
mybatis:
  typeAliasesPackage: org.ko.prototype.data.*.domain #小名
  mapperLocations: classpath:mappers/*.xml  #mapper扫描
  configuration:
    mapUnderscoreToCamelCase: true #开始下划线转驼峰

# 通用mapper配置
mapper:
  not-empty: true #
  before: true #
  mappers: tk.mybatis.mapper.common.Mapper #配置的mapper


prototype:
  security:
