server.port: 1337

spring:
  application.name: sigma-generator
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: sunniwell
    url: jdbc:h2:sunniwell:sos

# 生成工具配置
sigma.generator:
  prefix: t_
  entity:
    module: sigma-mysql
    rootPackage: org.ko.sigma.data
    entityTemplate: entity.java.ftl
    constantsTemplate: constants.java.ftl



