server.servlet:
  context-path: /sigma
#配置文件默认dev
spring:
  application.name: sigma-browser
  profiles:
    active: dev
  data:
    redis:
      repositories:
        enabled: false
management:
  health:
    redis:
      enabled: false # 禁用Redis健康检查



