server.port: 1338

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///sigma_server?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: tiger


sigma:
  file:
    folder: C://tmp/resources/

log.path: C://tmp/log
