server.servlet:
  context-path: /sigma

#配置文件默认dev
spring:
  profiles:
    active: dev
  data:
    redis:
      repositories:
        enabled: false

management:
  health:
    redis:
      enabled: false # 禁用Redis健康检查


# 关闭security默认
security.basic.enabled: false

# mybatis 配置
mybatis-plus:
  mapper-locations: classpath:org/ko/segma/rest/**/repository/*.xml  #mapper xml扫描
  typeAliasesPackage: org.ko.segma.data.*.domain #小名

mybatis.configuration.mapUnderscoreToCamelCase: true

# 通用mapper配置
mapper:
  not-empty: true #
  before: true #
  mappers: tk.mybatis.mapper.common.Mapper #配置的mapper

sigma:
  security:



