server.port: 1337

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///sigma_server?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: tiger


sigma:
  file:
    folder: D://tmp/resources/

log.path: D://tmp/log