spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql:///sigma_server?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    username: root
    password: tiger

log.path: /tmp/log